import React, { useEffect } from 'react'
import { View,Text,HStack, Divider, ScrollView } from 'native-base'
import { StyleSheet,TouchableOpacity } from 'react-native'
import { widthPercentageToDP as wp } from 'react-native-responsive-screen';
import IonIcons from 'react-native-vector-icons/Ionicons';
import Icon from 'react-native-vector-icons/FontAwesome';
import { useNavigation } from '@react-navigation/native';
import RenderHTML from 'react-native-render-html';
const Privacy = () => {

const Navigation=useNavigation()
const source={
    html:
    `
    <h2 className="cols__main-title cols__main-title--top container">Introduction</h2>

    <p className="p1 container">
    Welcome to All-Cures. Etherium Technologies hereinafter called as ETPL (“us”, “we”, or “our”) operates<a href="https://www.all-cures.com"> www.all-cures.com </a>(hereinafter referred to as “Service”). Our Privacy Policy governs your visit to <a href="https://www.all-cures.com">www.all-cures.com,</a> and explains how we collect, safeguard and disclose information that results from your use of our Service. We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions. Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“agreement”).</p><br/>
    
    <h2 className="cols__main-title cols__main-title--top" container >Definitions</h2>
    
    <p className="p1" container  >SERVICE means <a href="https://www.all-cures.com">www.all-cures.com </a>
    PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession). USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit). 
    COOKIES are small files stored on your device (computer or mobile device). 
    DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data. 
    DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively. 
    DATA SUBJECT is any living individual who is the subject of Personal Data. 
    THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
    </p><br/>
    
    <h2 className="cols__main-title cols__main-title--top container" >Information Collection and Use</h2>
    <p className="p1 container" >We collect several different types of information for various purposes to provide and improve our Service to you.</p><br/>
    
    <h2 className="cols__main-title cols__main-title--top container">Types of Data Collected</h2>
    <p className='p1 container'><b>Personal Data</b><br/>
    While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:<br/>
    •	Email address<br/>
    •	First name and last name<br/>
    •	Cookies and Usage Data<br/>
    We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by emailing us at  <a href="mailto:support@all-cures.com">support@all-cures.com</a>.<br/>
    <b>Usage Data</b><br/>
    We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device (“Usage Data”).<br/>
    This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.<br/>
    When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.<br/>
    <b>Tracking Cookies Data</b><br/>
    We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.<br/>
    Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.<br/>
    You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.<br/>
    Examples of Cookies we use:<br/>
    •	Session Cookies: We use Session Cookies to operate our Service.<br/>
    •	Preference Cookies: We use Preference Cookies to remember your preferences and various settings.<br/>
    •	Security Cookies: We use Security Cookies for security purposes.<br/>
    •	Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.<br/>
    •	Use of Data<br/>
    ETPL uses the collected data for various purposes:<br/>
    •	to provide and maintain our Service;<br/>
    •	to notify you about changes to our Service;<br/>
    •	to allow you to participate in interactive features of our Service when you choose to do so;<br/>
    •	to provide customer support;<br/>
    •	to gather analysis or valuable information so that we can improve our Service;<br/>
    •	to monitor the usage of our Service;<br/>
    •	to detect, prevent and address technical issues;<br/>
    •	to fulfill any other purpose for which you provide it;<br/>
    •	to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;<br/>
    •	to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;<br/>
    •	to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;<br/>
    •	in any other way we may describe when you provide the information;<br/>
    •	for any other purpose with your consent.<br/>
    •	Retention of Data<br/>
    We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies<br/>
    We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p><br/>
    
    
    
    <h2 className="cols__main-title cols__main-title--top container">Transfer of Data</h2>
    <p className='p1 container'>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies</p><br/>
    <h2 className="cols__main-title cols__main-title--top container">Disclosure of Data</h2>
    <p className='p1 container'>We may disclose personal information that we collect, or you provide.</p><br/>
    <h2 className="cols__main-title cols__main-title--top container">Disclosure for Law Enforcement.</h2>
    <p className="p1 container">Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</p><br/>
    <h2 className="cols__main-title cols__main-title--top container">Business Transaction.</h2>
    <p className="p1 container">If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.<br/>
    Other cases. We may disclose your information also:<br/>
    •	to our subsidiaries and affiliates;<br/>
    •	for the purpose of including your company’s logo on our website;<br/>
    •	Security of Data<br/>
    The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p><br/>
    <h2 className="cols__main-title cols__main-title--top container">Service Providers</h2>
    <p className="p1 container" >We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services or assist us in analyzing how our Service is used.<br/>
    These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p><br/>
    <h2 className="cols__main-title cols__main-title--top container">Analytics</h2>
    <p className="p1 container">We may use third-party Service Providers to monitor and analyze the use of our Service.<br/>
    Google Analytics<br/>
    Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.<br/>
    For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: <a href="https://policies.google.com/privacy?hl=en
    ">https://policies.google.com/privacy?hl=en
    </a><br/>
    We also encourage you to review the Google's policy for safeguarding your data: <a href="https://support.google.com/analytics/answer/6004245">https://support.google.com/analytics/answer/6004245</a>.</p><br/>
    <h2 className="cols__main-title cols__main-title--top container">Changes to This Privacy Policy</h2>
    <p className="p1 container">We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.<br/>
    We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.<br/>
    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p><br/>
    <h2 className="cols__main-title cols__main-title--top container">Contact Us</h2>
    <p className='p1 container'>If you have any questions about this Privacy Policy, please contact us:<br/>
    By email: <a href="mailto:support@all-cures.com">support@all-cures.com</a>.<br/>
    By visiting this page on our website: <a href="https://www.all-cures.com">www.all-cures.com</a>.</p>`
}

  return (
 <View style={{padding:10,backgroundColor:'white',flex:1}}>
    <ScrollView>
    <View style={styles.header}>
<Text style={styles.headerText}>
    Privacy Policy
</Text>
    </View>
<View style={styles.setting}>
<RenderHTML
contentWidth={wp('100%')}
source={source}
   tagsStyles = {{ adjustsFontSizeToFit:true,

    body:{color:'#00415e'}
 }}

/>
</View>
</ScrollView>
 </View>

  )
}

export default Privacy

const styles=StyleSheet.create({
    setting:{
        backgroundColor:'aliceblue',
        borderRadius:15,
        height:'100%',
        width:'100%',
        padding:10,
    },
    item:{
   paddingVertical:17,
   marginRight:20,
   flexDirection:'row',
   justifyContent:'space-between'
    },
    header:{
  padding:15
    },
    headerText:{
        fontFamily:'Raleway-Bold',
   fontSize:wp('5.5%'),
   marginTop:5,
   color:'#00415e'
      
    }
})